name: Deploy Source Code

on:
  push:
    branches: [ develop ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source-code
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: "*"
          target: "../test/"
          # script: whoami

  job2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Create folder
        run: |
          cd .. && mkdir test3/


  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 22
        username: ${{ secrets.SSH_USERNAME }}
        # password: 'password'
        localPath: './'
        remotePath: '../test3/'