name: Deploy Source Code

on:
  push:
    branches: [ develop ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source-code
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: "*"
          target: "../test/"
          # script: whoami

  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Create folder
        run: |
          cd .. && mkdir -p myNewFolder/myNewSubFolder && cp -R dist myNewFolder/myNewSubFolder
          ls myNewFolder/MyNewSubFolder

