name: Deploy Source Code

on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source-code
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        with:
          source: "*"
          target: "../test/"
          script: whoami
