name: Deploy Source Code

on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source-code
        uses: actions/checkout@v2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "*"
          target: "/root"

  # sync:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Add remote
  #       run: git remote add overhangio https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@git.overhang.io/core/indigo.git
  #     - name: Push
  #       run: git push overhangio master
